name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java (Maven or Gradle, depending on your project)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build with Maven (or Gradle)
      - name: Build with Maven
        run: mvn clean install

      # List files in target directory for debugging
      - name: List files in target directory
        run: ls -l target/

      # Set up Google Cloud SDK
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SPRINGBOOT }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp

      # Push Docker Image to GCR
      - name: Push Docker Image to GCR
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp

      # Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy demo-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
